/* generated by tools/import_ngcc.py - instance configuration */
#ifndef NGCC_CONFIG_H
#define NGCC_CONFIG_H
#define NGCC_M4 1
#define NGCC_INSTANCE_NAME "NEV-C2"
#ifndef NDEBUG
#define NDEBUG 1
#endif
#ifndef USE_ICCS
#define USE_ICCS
#endif
#ifndef PARAMS
#define PARAMS 11
#endif
#include "ngcc_compat.h"
#endif /* NGCC_CONFIG_H */
