/* generated by tools/import_ngcc.py - instance configuration */
#ifndef NGCC_CONFIG_H
#define NGCC_CONFIG_H
#define NGCC_M4 1
#define NGCC_INSTANCE_NAME "lwrdsa192"
#ifndef NDEBUG
#define NDEBUG 1
#endif
#ifndef XOF_168
#define XOF_168 168
#endif
#ifndef XOF_136
#define XOF_136 136
#endif
#include "ngcc_compat.h"
#endif /* NGCC_CONFIG_H */
