/* generated by tools/import_ngcc.py - instance configuration */
#ifndef NGCC_CONFIG_H
#define NGCC_CONFIG_H
#define NGCC_M4 1
#define NGCC_INSTANCE_NAME "Scloudplus-256-SM3"
#ifndef NDEBUG
#define NDEBUG 1
#endif
#ifndef SCLOUDPLUS_TIER_REFERENCE
#define SCLOUDPLUS_TIER_REFERENCE
#endif
#ifndef SCLOUDPLUS_FAMILY_SM3
#define SCLOUDPLUS_FAMILY_SM3
#endif
#ifndef SCLOUDPLUS_REF_FAMILY_SM3
#define SCLOUDPLUS_REF_FAMILY_SM3
#endif
#include "ngcc_compat.h"
#endif /* NGCC_CONFIG_H */
