/* generated by tools/import_ngcc.py - instance configuration */
#ifndef NGCC_CONFIG_H
#define NGCC_CONFIG_H
#define NGCC_M4 1
#define NGCC_INSTANCE_NAME "Galas-512S"
#ifndef NDEBUG
#define NDEBUG 1
#endif
#ifndef _POSIX_C_SOURCE
#define _POSIX_C_SOURCE 200809L
#endif
#ifndef GALAS_INSTANCE
#define GALAS_INSTANCE GALAS_512S
#endif
#ifndef GALAS_INSTANCE_NAME
#define GALAS_INSTANCE_NAME "Galas-512S"
#endif
#include "ngcc_compat.h"
#endif /* NGCC_CONFIG_H */
