/* generated by tools/import_ngcc.py - instance configuration */
#ifndef NGCC_CONFIG_H
#define NGCC_CONFIG_H
#define NGCC_M4 1
#define NGCC_INSTANCE_NAME "Mithril-256"
#ifndef NDEBUG
#define NDEBUG 1
#endif
#ifndef RRLWR_SECURITY_LEVEL
#define RRLWR_SECURITY_LEVEL 256
#endif
#ifndef RRLWR_PACKING_16BIT_SCALAR
#define RRLWR_PACKING_16BIT_SCALAR 1
#endif
#include "ngcc_compat.h"
#endif /* NGCC_CONFIG_H */
