# generated by tools/import_ngcc.py
IMPL_DEPS_crypto_kex_CreTAKE-K2K-PLAC512_ref := crypto_kem/POLARLAC-512/ref
IMPL_DEP_KEEP_crypto_kex_CreTAKE-K2K-PLAC512_ref := kem_* PKE_* Encode_m Decode_m mq_poly_* pack_c2_dbit unpack_c2_dbit poly_compress_c2 poly_decompress_c2 polyvec_decompress polyvec_byte_decompress
