# generated by tools/import_ngcc.py; edited by hand:
# the official KAT_SIG_Phoenix-SHAKE-*.txt vectors were produced with the ICCS
# SM3 DRNG (common/drng.c), so the submission's SHAKE256 DRNG copy is left out.
IMPL_EXCLUDE_SRC_crypto_sign_Phoenix-SHAKE-512f_ref := crypto_sign/Phoenix-SHAKE-512f/ref/phoenix_drng.c
