/* generated by tools/import_ngcc.py - instance configuration */
#ifndef NGCC_CONFIG_H
#define NGCC_CONFIG_H
#define NGCC_M4 1
#define NGCC_INSTANCE_NAME "BW_KEM_C512"
#ifndef NDEBUG
#define NDEBUG 1
#endif
#ifndef BWKEM_C512_USE_ICCS_AUXFUNC
#define BWKEM_C512_USE_ICCS_AUXFUNC
#endif
#include "ngcc_compat.h"
#endif /* NGCC_CONFIG_H */
