/* generated by tools/import_ngcc.py - instance configuration */
#ifndef NGCC_CONFIG_H
#define NGCC_CONFIG_H
#define NGCC_M4 1
#define NGCC_INSTANCE_NAME "TRINE-128-balanced"
#ifndef NDEBUG
#define NDEBUG 1
#endif
#ifndef USE_ICCS
#define USE_ICCS
#endif
#ifndef PARAMS
#define PARAMS 1
#endif
#ifndef TRINE_ALGORITHM_INSTANCE
#define TRINE_ALGORITHM_INSTANCE "MEDS2endGen-Balanced-I"
#endif
#include "ngcc_compat.h"
#endif /* NGCC_CONFIG_H */
