/* generated by tools/import_ngcc.py - instance configuration */
#ifndef NGCC_CONFIG_H
#define NGCC_CONFIG_H
#define NGCC_M4 1
#define NGCC_INSTANCE_NAME "CEDRUSC-512f"
#ifndef NDEBUG
#define NDEBUG 1
#endif
#ifndef PARAMS
#define PARAMS cedrusc-sm3-512f
#endif
#include "ngcc_compat.h"
#endif /* NGCC_CONFIG_H */
