/* stub generated by tools/import_ngcc.py: Weaver includes randombytes.h without shipping it */
#ifndef RANDOMBYTES_H
#define RANDOMBYTES_H
#include <stddef.h>
int randombytes(unsigned char *out, size_t outlen);
#endif
