/* generated by tools/import_ngcc.py - instance configuration */
#ifndef NGCC_CONFIG_H
#define NGCC_CONFIG_H
#define NGCC_M4 1
#define NGCC_INSTANCE_NAME "HARE-256-kr"
#ifndef NDEBUG
#define NDEBUG 1
#endif
#ifndef HARE_BACKEND_KR
#define HARE_BACKEND_KR
#endif
#ifndef HARE_SYMMETRIC_MODE_B
#define HARE_SYMMETRIC_MODE_B
#endif
#include "ngcc_compat.h"
#endif /* NGCC_CONFIG_H */
