/* generated by tools/import_ngcc.py - instance configuration */
#ifndef NGCC_CONFIG_H
#define NGCC_CONFIG_H
#define NGCC_M4 1
#define NGCC_INSTANCE_NAME "Octarine-128"
#ifndef NDEBUG
#define NDEBUG 1
#endif
#ifndef RRLWR_SECURITY_LEVEL
#define RRLWR_SECURITY_LEVEL 128
#endif
#include "ngcc_compat.h"
#endif /* NGCC_CONFIG_H */
