/* generated by tools/import_ngcc.py - instance configuration */
#ifndef NGCC_CONFIG_H
#define NGCC_CONFIG_H
#define NGCC_M4 1
#define NGCC_INSTANCE_NAME "AFS_KEX_C128"
#ifndef NDEBUG
#define NDEBUG 1
#endif
#ifndef BWKEM128_INTERNAL_COMPAT
#define BWKEM128_INTERNAL_COMPAT
#endif
#ifndef BWKEM_C128_USE_ICCS_AUXFUNC
#define BWKEM_C128_USE_ICCS_AUXFUNC
#endif
#include "ngcc_compat.h"
#endif /* NGCC_CONFIG_H */
