/* generated by tools/import_ngcc.py - instance configuration */
#ifndef NGCC_CONFIG_H
#define NGCC_CONFIG_H
#define NGCC_M4 1
#define NGCC_INSTANCE_NAME "Aigis-Enc-II"
#ifndef NDEBUG
#define NDEBUG 1
#endif
#ifndef USE_NICCS_API
#define USE_NICCS_API
#endif
#ifndef PARAMS
#define PARAMS 2
#endif
#include "ngcc_compat.h"
#endif /* NGCC_CONFIG_H */
