/* generated by tools/import_ngcc.py - instance configuration */
#ifndef NGCC_CONFIG_H
#define NGCC_CONFIG_H
#define NGCC_M4 1
#define NGCC_INSTANCE_NAME "ReSolveD-alpha-256f"
#ifndef NDEBUG
#define NDEBUG 1
#endif
#ifndef WITH_KECCAK_X4
#define WITH_KECCAK_X4
#endif
#ifndef XOF_PSEUDO
#define XOF_PSEUDO
#endif
#include "ngcc_compat.h"
#endif /* NGCC_CONFIG_H */
