/* generated by tools/import_ngcc.py - instance configuration */
#ifndef NGCC_CONFIG_H
#define NGCC_CONFIG_H
#define NGCC_M4 1
#define NGCC_INSTANCE_NAME "ublockith_d3_256s"
#ifndef NDEBUG
#define NDEBUG 1
#endif
#ifndef USE_BALLET
#define USE_BALLET 1
#endif
#ifndef HAVE_BALLET_CORE
#define HAVE_BALLET_CORE 1
#endif
#include "ngcc_compat.h"
#endif /* NGCC_CONFIG_H */
