/* generated by tools/import_ngcc.py - instance configuration */
#ifndef NGCC_CONFIG_H
#define NGCC_CONFIG_H
#define NGCC_M4 1
#define NGCC_INSTANCE_NAME "WeaverKEM-512"
#ifndef NDEBUG
#define NDEBUG 1
#endif
#ifndef WEAVER_MODE
#define WEAVER_MODE 5
#endif
#include "ngcc_compat.h"
#endif /* NGCC_CONFIG_H */
