/* generated by tools/import_ngcc.py - instance configuration */
#ifndef NGCC_CONFIG_H
#define NGCC_CONFIG_H
#define NGCC_M4 1
#define NGCC_INSTANCE_NAME "MAMBA-Viper-256"
#ifndef NDEBUG
#define NDEBUG 1
#endif
#ifndef VIPER_LEVEL
#define VIPER_LEVEL 256
#endif
#ifndef VIPER_USE_E8_CODEC
#define VIPER_USE_E8_CODEC 1
#endif
#include "ngcc_compat.h"
#endif /* NGCC_CONFIG_H */
