/* generated by tools/import_ngcc.py - instance configuration */
#ifndef NGCC_CONFIG_H
#define NGCC_CONFIG_H
#define NGCC_M4 1
#define NGCC_INSTANCE_NAME "sydo_256f"
#ifndef NDEBUG
#define NDEBUG 1
#endif
#ifndef SYDO_REF_NGCC
#define SYDO_REF_NGCC
#endif
#include "ngcc_compat.h"
#endif /* NGCC_CONFIG_H */
