/* generated by tools/import_ngcc.py - instance configuration */
#ifndef NGCC_CONFIG_H
#define NGCC_CONFIG_H
#define NGCC_M4 1
#define NGCC_INSTANCE_NAME "bag_piglet_512"
#ifndef NDEBUG
#define NDEBUG 1
#endif
#ifndef BAG_PIGLET_KAT
#define BAG_PIGLET_KAT
#endif
#include "ngcc_compat.h"
#endif /* NGCC_CONFIG_H */
