/* generated by tools/import_ngcc.py - instance configuration */
#ifndef NGCC_CONFIG_H
#define NGCC_CONFIG_H
#define NGCC_M4 1
#define NGCC_INSTANCE_NAME "Phoenix-SM3-128s"
#ifndef NDEBUG
#define NDEBUG 1
#endif
#ifndef PARAMS
#define PARAMS phoenix-sm3-128s
#endif
#ifndef ALLOW_DEEP_TREES
#define ALLOW_DEEP_TREES
#endif
#ifndef SUBMISSION_DRNG
#define SUBMISSION_DRNG
#endif
#ifndef PARAMNAME
#define PARAMNAME "Phoenix-SM3-128s"
#endif
#include "ngcc_compat.h"
#endif /* NGCC_CONFIG_H */
