/* generated by tools/import_ngcc.py - instance configuration */
#ifndef NGCC_CONFIG_H
#define NGCC_CONFIG_H
#define NGCC_M4 1
#define NGCC_INSTANCE_NAME "sm4th_d3_128f_loose"
#ifndef NDEBUG
#define NDEBUG 1
#endif
#ifndef SM4_SBOX_TABLE
#define SM4_SBOX_TABLE
#endif
#include "ngcc_compat.h"
#endif /* NGCC_CONFIG_H */
