/* generated by tools/import_ngcc.py - instance configuration */
#ifndef NGCC_CONFIG_H
#define NGCC_CONFIG_H
#define NGCC_M4 1
#define NGCC_INSTANCE_NAME "vistrutith_d3_512f"
#ifndef NDEBUG
#define NDEBUG 1
#endif
#ifndef SBOX_TABLE
#define SBOX_TABLE
#endif
#include "ngcc_compat.h"
#endif /* NGCC_CONFIG_H */
