/* generated by tools/import_ngcc.py - instance configuration */
#ifndef NGCC_CONFIG_H
#define NGCC_CONFIG_H
#define NGCC_M4 1
#define NGCC_INSTANCE_NAME "QingLuan-512"
#ifndef NDEBUG
#define NDEBUG 1
#endif
#ifndef QINGLUAN_512
#define QINGLUAN_512
#endif
#include "ngcc_compat.h"
#endif /* NGCC_CONFIG_H */
