/* generated by tools/import_ngcc.py - instance configuration */
#ifndef NGCC_CONFIG_H
#define NGCC_CONFIG_H
#define NGCC_M4 1
#define NGCC_INSTANCE_NAME "Lore-SM3-L3"
#ifndef NDEBUG
#define NDEBUG 1
#endif
#ifndef LORE_LEVEL
#define LORE_LEVEL 3
#endif
#ifndef LORE_USE_API_PKC_DRNG
#define LORE_USE_API_PKC_DRNG
#endif
#include "ngcc_compat.h"
#endif /* NGCC_CONFIG_H */
